-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 11:15:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_incluijobs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_incluijobs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_incluijobs` DEFAULT CHARACTER SET utf8 ;
USE `db_incluijobs` ;

-- -----------------------------------------------------
-- Table `db_incluijobs`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_incluijobs`.`tb_tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL COMMENT 'Campo para descrever se a postagem é para buscar emprego ou oferecer emprego',
  `grupo` VARCHAR(255) NOT NULL COMMENT 'Campo para indicar a qual grupo o candidato faz parte (LGBTQIAP+, pessoas pretas e pardas, indígenas, etc...)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_incluijobs`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_incluijobs`.`tb_usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL COMMENT 'Nome do usuário',
  `usuario` VARCHAR(255) NOT NULL COMMENT 'E-mail de login',
  `senha` VARCHAR(255) NOT NULL COMMENT 'Senha para acesso à plataforma',
  `foto` VARCHAR(255) NOT NULL COMMENT 'Foto de perfil',
  `cpf` VARCHAR(14) NULL COMMENT 'CPF do candidato',
  `cnpj` VARCHAR(18) NULL COMMENT 'CNPJ da empresa empregadora',
  `dtnascimento` DATE NULL COMMENT 'Data de nascimento do candidato',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_incluijobs`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_incluijobs`.`tb_postagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cabecalho/titulo` VARCHAR(255) NOT NULL COMMENT 'Título da postagem',
  `descricao` VARCHAR(255) NOT NULL COMMENT 'Texto da postagem',
  `status` VARCHAR(255) NULL COMMENT 'Ativo ou inativo',
  `privacidade` VARCHAR(255) NULL COMMENT 'Público, apenas contatos ou privado.',
  `anexo` VARCHAR(255) NULL COMMENT 'Incluir links, arquivos, imagens ou vídeos.',
  `tb_tema_id` BIGINT NOT NULL,
  `tb_usuarios_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagem_tb_tema_idx` (`tb_tema_id` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_usuarios1_idx` (`tb_usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_tema`
    FOREIGN KEY (`tb_tema_id`)
    REFERENCES `db_incluijobs`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_usuarios1`
    FOREIGN KEY (`tb_usuarios_id`)
    REFERENCES `db_incluijobs`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
